# Generated by Django 4.2.6 on 2023-10-21 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Enter Brand name', max_length=255)),
                ('body_shape', models.CharField(choices=[('suv', 'S-U-V'), ('sedan', 'Sedan'), ('small_car', 'Small Car or Convertible'), ('van_minibus', 'VAN/Minibus'), ('transporter', 'Transporter')], default='sedan', help_text="Choice your car's body shape", max_length=255)),
                ('model', models.CharField(help_text="Enter your car's model", max_length=255)),
                ('license_plate', models.CharField(help_text="Enter your car's license plate. EX:(HQ327QH)", max_length=7)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('full_clean', 'Full Service:(Included Detailing)'), ('detailing', 'Detailing'), ('engine_clean', 'Engine Depressing & Coating'), ('ac_treatment', 'A.C. Treatment'), ('internal_cleaning', 'Intensive internal cleaning(dry)'), ('body_wash', 'Body Shampooing and Washing')], default='body_wash', help_text='Choice Service', max_length=255)),
                ('booking_datetime', models.DateTimeField(help_text='Choose the date and time of your visit')),
                ('choose_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.createvehicle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
